### ISSUE TITLE
Able to compile but not to run

### ISSUE THREAD

**Issue by jeangui** [catalinmiron/react-native-dribbble-app#20]
Hi,

I wanted to test your sample application but I am confronted to a problem: I am not able to run it.

I have got an error:

/Users/houitte/SANDBOX/REACT/react-native-dribbble-app/node_modules/react-native/Libraries/Image/RCTDownloadTaskWrapper.m:65:49: Null passed to a callee that requires a non-null argument

What have I missed ?

Thanks in advance for the help.

Best
jeangui

**Comment by gold3bear** [comment]
change `NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url completionHandler:nil];` to `NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url];`

**Comment by jeangui** [comment]
thanks a lot. it did work. :)

best
