### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by suhaotian** [catalinmiron/react-native-dribbble-app#21]
![image](https://cloud.githubusercontent.com/assets/6512574/11324910/429e01da-917a-11e5-8e4c-6ed6a47e4534.png)

**Comment by catalinmiron** [comment]
Check #20. I'm working on upgrading this and everything should work seamless. Thanks for checking this app.

> change NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url completionHandler:nil]; to NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url];

**Comment by suhaotian** [comment]
@catalinmiron nice, work
