### ISSUE TITLE
Hi can you pls explain this code to me pls?thx!

### ISSUE THREAD

**Issue by zzz6519003** [catalinmiron/react-native-dribbble-app#8]
``` js
var {
  Image,
  PixelRatio,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Component
} = React;
```

what does it do?

**Comment by catalinmiron** [comment]
Hi @zzz6519003 ,

These are React Native Components. You can check [Facebook's React Native docs](https://facebook.github.io/react-native/docs/getting-started.html) for further informations.

**Comment by zzz6519003** [comment]
so basically it's gonna import just these things   `Image,
  PixelRatio,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Component
`

into the thing called react?

**Comment by catalinmiron** [comment]
> into the thing called react? 

No, you import the components **from** `React`

**Comment by lwansbrough** [comment]
@zzz6519003 This is called object destructuring. It's basically saying, "pull out the following properties from this object, each as their own variable."

**Comment by zzz6519003** [comment]
Hey man, here's your beer! :beer:  catch!

**Comment by catalinmiron** [comment]
@lwansbrough :+1: you have a :cookie:
