### ISSUE TITLE
Install fails with react-native 0.4.2 

### ISSUE THREAD

**Issue by bteng22** [catalinmiron/react-native-dribbble-app#9]
```
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/Cellar/iojs/2.3.3/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.3.3
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-modal@0.3.8 wants react-native@>=0.4.3
npm ERR! peerinvalid Peer react-native-parallax-view@2.0.2 wants react-native@>=0.8.0 || 0.8.0-rc || 0.8.0-rc.2 || 0.8.0-rc.3
npm ERR! peerinvalid Peer react-native-vector-icons@0.6.6 wants react-native@>=0.4.0 || 0.5.0-rc1 || 0.6.0-rc || 0.7.0-rc || 0.7.0-rc.2 || 0.8.0-rc || 0.8.0-rc.2
```

**Comment by catalinmiron** [comment]
Yes, i'll fix it as soon as I'll have some free time, unfortunately i'm quite busy, but in #1 i'll update the dependencies. Thanks for checking it

**Comment by bteng22** [comment]
No problem at all—thank for letting me know. Looking forward to it !

**Comment by guilhermedecampo** [comment]
After updating dependencies,
seems that the fonts-icons(.ttf) are missing too. =/

**Comment by pickhardt** [comment]
I'm getting the same thing...

```
npm ERR! argv "/usr/local/Cellar/iojs/2.3.0/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.3.0
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-modal@0.3.8 wants react-native@>=0.4.3
npm ERR! peerinvalid Peer react-native-parallax-view@2.0.2 wants react-native@>=0.8.0 || 0.8.0-rc || 0.8.0-rc.2 || 0.8.0-rc.3
npm ERR! peerinvalid Peer react-native-vector-icons@0.6.8 wants react-native@>=0.4.0 || 0.5.0-rc1 || 0.6.0-rc || 0.7.0-rc || 0.7.0-rc.2 || 0.8.0-rc || 0.8.0-rc.2 || 0.9.0-rc
```

What I don't understand is why this happens. Any version >=0.4.3, >=0.8.0, and >= 0.4.0 should be acceptable, I'd think.

**Comment by guilhermedecampo** [comment]
You should change the react-native to 0.8.0. @pickhardt. 
BUT I think the icons package are missing too

**Comment by catalinmiron** [comment]
Guys,

Can you pull the latest master ? I manage to update the react-native packages. Known issues:

![dribbble-app-build-issue](https://cloud.githubusercontent.com/assets/2805320/9275996/e99f9cd4-42a9-11e5-9ac8-241edd812701.gif)

**Comment by guilhermedecampo** [comment]
Awesome @catalinmiron! Will try out.

**Comment by guilhermedecampo** [comment]
Confirm that bug. But everything works fine!

Thanks for this effort.. Really good study react native with your source-code.

**Comment by catalin-miron-hs** [comment]
@guilhermedecampo Thanks man !
